const ROUTES = {
  home: '/',
  login: '/auth/login',
  dashboard: {
    Partners:      '/dashboard/partners',
    addPartner:    '/dashboard/partners/add',
    partnerEdit:   (id: number | string) => `/dashboard/partners/${id}/edit`,
    banners:       '/dashboard/banner',
    bannerAdd:     '/dashboard/banner/add',
    bannerEdit:    (id: number | string) => `/dashboard/banner/${id}/edit`,
    subcategories: '/dashboard/subcategory',
    subcategoryAdd: '/dashboard/subcategory/add',
    subcategoryEdit: (id: number | string) => `/dashboard/subcategory/${id}/edit`,
    overview:      '/dashboard',
    admin:         '/dashboard/admin',
    adminAdd:      '/dashboard/admin/add',
    adminEdit:     (id: number | string) => `/dashboard/admin/${id}/edit`,
    users:         '/dashboard/user',
    userAdd:       '/dashboard/user/add',
    userEdit:      (id: number | string) => `/dashboard/user/${id}/edit`,
    categories:    '/dashboard/category',
    categoryAdd:   '/dashboard/category/add',
    categoryEdit:  (id: number | string) => `/dashboard/category/${id}/edit`,
    cities:        '/dashboard/city',
    cityAdd:       '/dashboard/city/add',
    cityEdit:      (id: number | string) => `/dashboard/city/${id}/edit`,
    zones:         '/dashboard/zone',
    zoneAdd:       '/dashboard/zone/add',
    zoneEdit:      (id: number | string) => `/dashboard/zone/${id}/edit`,
    products:      '/dashboard/product',
    productAdd:    '/dashboard/product/add',
    productEdit:   (id: number | string) => `/dashboard/product/${id}/edit`,
    paymentMethods:'/dashboard/paymentmethod',
    paymentMethodAdd: '/dashboard/paymentmethod/add',
    paymentMethodEdit: (id: number | string) => `/dashboard/paymentmethod/${id}/edit`,
    orders:        '/dashboard/order',
    orderDetails:  (id: number | string) => `/dashboard/order/${id}`,
    coupons:       '/dashboard/coupon',
    couponAdd:     '/dashboard/coupon/add',
    couponEdit:    (id: number | string) => `/dashboard/coupon/${id}/edit`,
    Settings:      '/dashboard/settings',
    About:         '/dashboard/about',
    Contact:       '/dashboard/contact',
    Service:       '/dashboard/service',
    serviceAdd:    '/dashboard/service/add',
    addservice:    '/dashboard/service/add',
    serviceEdit:   (id: number | string) => `/dashboard/service/${id}/edit`,
  },
};

export default ROUTES;
